name: Nightly-build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: ['6.0.x']

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version:  ${{ matrix.dotnet-version }}
    - name: Restore NuGet Packages
      run: nuget restore
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - uses: papeloto/action-zip@v1
      with:
        files: RageCoop.Client/bin/Release
        dest: RageCoop.Client.zip
    - uses: actions/upload-artifact@v3
      with:
        name: RageCoop.Client.zip
        path: RageCoop.Client.zip
    - uses: actions/checkout@v2
      
