name: Nightly-build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: ['6.0.x']

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version:  ${{ matrix.dotnet-version }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build client
      run: dotnet build RageCoop.Client/RageCoop.Client.csproj --no-restore --configuration Release
    - name: Build server win-x64
      run: dotnet publish RageCoop.Server/RageCoop.Server.csproj --self-contained -p:PublishSingleFile=true -p:PublishReadyToRun=true -p:PublishTrimmed=true -r win-x64 -o RageCoop.Server/bin/Release/net6.0/publish/win-x64
    - uses: actions/upload-artifact@v3
      with:
        name: RageCoop.Client
        path: RageCoop.Client/bin/Release
    - uses: actions/upload-artifact@v3
      with:
        name: RageCoop.Server-win-x64
        path: RageCoop.Server/bin/Release/net6.0/publish/win-x64
    - uses: actions/checkout@v2
      
