name: Nightly-build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: ['6.0.x']

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version:  ${{ matrix.dotnet-version }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build client
      run: dotnet build RageCoop.Client/RageCoop.Client.csproj --no-restore --configuration Release -o RageCoop.Client/bin/RageCoop
    - name: Build server win-x64
      run: dotnet publish RageCoop.Server/RageCoop.Server.csproj --self-contained -p:PublishSingleFile=true -p:PublishTrimmed=true -r win-x64 -o RageCoop.Server/bin/win-x64 -c Release
    - name: Build server linux-x64
      run: dotnet publish RageCoop.Server/RageCoop.Server.csproj --self-contained -p:PublishSingleFile=true -p:PublishTrimmed=true -r linux-x64 -o RageCoop.Server/bin/linux-x64 -c Release
    - name: Build server linux-arm
      run: dotnet publish RageCoop.Server/RageCoop.Server.csproj --self-contained -p:PublishSingleFile=true -p:PublishTrimmed=true -r linux-arm -o RageCoop.Server/bin/linux-arm -c Release
    - uses: vimtor/action-zip@v1
      with:
        files: RageCoop.Client/bin
        dest: RageCoop.Client.zip
    - uses: actions/upload-artifact@v3
      with:
        name: RageCoop.Server-win-x64
        path: RageCoop.Server/bin/win-x64
    - uses: actions/upload-artifact@v3
      with:
        name: RageCoop.Server-linux-x64
        path: RageCoop.Server/bin/linux-x64
    - uses: actions/upload-artifact@v3
      with:
        name: RageCoop.Server-linux-arm
        path: RageCoop.Server/bin/linux-arm

    - uses: WebFreak001/deploy-nightly@v1.1.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # automatically provided by github actions
      with:
        upload_url: https://uploads.github.com/repos/RAGECOOP/RAGECOOP-V/releases/70603992/assets{?name,label} 
        release_id: 70603992 
        asset_path: RageCoop.Client.zip
        asset_name: RageCoop.Client-nightly.zip
        asset_content_type: application/zip
        max_releases: 7
    - uses: actions/checkout@v2
      
